### ISSUE TITLE
Request dependency has been deprecated

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/sroc-service-team#1]
The [TCS](https://github.com/DEFRA/sroc-charging-service) currently uses the following dependencies

- [request](https://www.npmjs.com/package/request)
- [request-promise-native](https://www.npmjs.com/package/request-promise-native)

[PR #16](https://github.com/DEFRA/sroc-charging-service/pull/16) got them up to the latest versions. But they were both deprecated in Feb 2020 and no new changes or updates are being made to them.

We need to investigate what they are being used for and what we should be replacing these dependencies with.

**Comment by StuAA78** [comment]
TCS uses these solely to send requests to the rules service -- `request` is the library for making http requests and `request-promise-native` extends it to add promise support. The SRoC Charging Module API has adopted `got` as the http request library, which supports promises by default:

https://github.com/DEFRA/sroc-charging-module-api/blob/main/app/services/rules.service.js

**Comment by Cruikshanks** [comment]
We no longer make calls to the rules service via the charging service. That service is now redundant so this is no longer an issue.
