### ISSUE TITLE
Charging module deploys as `development`

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/sroc-service-team#18]
The deployment task definition for the Charging Module API we inherited sets the `NODE_ENV` to `development`.

Best practise is to set this to `production` as some packages rely on this information to govern how they behave. One obvious example is the logger. When set to `production` it outputs each log message in a single line assuming it will be aggregated or used by tools like AWS Cloudwatch (which we use). When set to anything else it prints each message over multiple lines because it assumes a developer is scanning the output.

**Comment by Cruikshanks** [comment]
Non-production environments fixed in https://gitlab-dev.aws-int.defra.cloud/sroc/sroc-jenkins/-/merge_requests/23

Just need to sort production.

**Comment by StuAA78** [comment]
This relates to the v1 `charging-module-api` service which has been superseded by the v2 `sroc-charging-module-api` service and therefore this won't be fixed.
