### ISSUE TITLE
Unhandled exceptions knock over service

### ISSUE THREAD

**Issue by Cruikshanks** [DEFRA/sroc-service-team#9]
We recently had an example of an unhandled error knocking over the service. In an AWS environment, this would mean the container would stop and ECS would start up another.

However, we really shouldn't let unhandled exceptions kill our service. We should be handling and logging them and making sure the client gets a proper response.

The [unhandled exception that kicked off this issue](https://github.com/DEFRA/charging-module-api/pull/89) has been dealt with.

But we need to

- confirm we don't have a mechanism for unhandled exceptions
- investigate the most appropriate way of doing it e.g. guides, work done by other teams etc

Once we have a firm idea of what needs doing we then can ensure the work is tracked and prioritised by the delivery team.

**Comment by StuAA78** [comment]
This relates to the v1 `charging-module-api` service which has been superseded by the v2 `sroc-charging-module-api` service and therefore this won't be fixed.
